routes/web.php
<?php

use App\Http\Controllers\AkomodasiController;
use App\Http\Controllers\EkrafController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\KunAkomodasiController;
use App\Http\Controllers\KunOwController;
use App\Http\Controllers\KunRhuController;
use App\Http\Controllers\OwController;
use App\Http\Controllers\RhuController;
use App\Http\Controllers\UserController;
use App\KunjunganAkomodasi;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['middleware' => 'auth'], function(){
    Route::get('/home', 'HomeController@index')->name('home');
    //##################AKOMODASI#######################
    Route::resource('akomodasi', 'AkomodasiController');
    Route::resource('k_akomodasi', 'KunAkomodasiController');
    Route::get('exportakomodasi/{tahun}', 'KunAkomodasiController@exportAkomodasi')->name('exportakomodasi');
    Route::post('akomodasi.migration', 'AkomodasiController@migration')->name('akomodasi.migration');

    //########### END OF AKOMODASI ROUTE ################

    //############################ OW ######################
    Route::resource('ow', 'OwController');
    Route::resource('k_ow', 'KunOwController');
    Route::get('exportow/{tahun}', 'KunOwController@exportOw')->name('exportow');
    Route::get('exportowasing/{tahun}', 'KunOwController@exportOwAsing')->name('exportowasing');
    Route::post('ow.migration', 'OwController@migration')->name('ow.migration');

    //############## END OF OW ####################

    //########## RHU #############
    Route::resource('rhu', 'RhuController');
    Route::resource('k_rhu', 'KunRhuController');
    Route::get('exportrhu/{tahun}', 'KunRhuController@exportRhu')->name('exportrhu');
    //########## END OF RHU ########

    //########### EKRAF ##################
    Route::resource('ekraf', 'EkrafController')->except('index');
    route::get('ekraf_index/{id}', 'EkrafController@index')->name('ekraf_index');
    Route::get('kurasi/{id}/{code}', 'EkrafController@kurasi')->name('kurasi');
    Route::get('export/{code}','EkrafController@export')->name('ekraf.export');
    Route::post('city', 'HomeController@city')->name('city');
    Route::post('district', 'HomeController@district')->name('district');
    Route::post('village', 'HomeController@village')->name('village');
    //######### END EKRAF ####################
    Route::resource('user', 'UserController');
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','level'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function kunjunganAkomodasi()
    {
        return $this->hasMany('App\KunjunganAkomodasi');
    }

    public function kunjunganOw()
    {
        return $this->hasMany('App\KunjunganOw');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use RealRashid\SweetAlert\Facades\Alert;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

   
    
    public function index()
    {
        $datas = User::get();
        return view('user.index')->with('datas', $datas);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate(request(), [
            'name' => 'required',
            'email' => 'required|email',
            'password' => 'required',
        ]);

        $check = User::whereEmail($request->get('email'))->count();
        if ($check > 0) {
            Alert::error('Gagal', 'Email telah ada');
            return redirect()->back();
        } else {
            $user = new User();
            $user->name = $request->get('name');
            $user->email = $request->get('email');
            $user->password = bcrypt($request->get('password'));
            $user->level = $request->get('level');
            $user->save();
            Alert::success('Sukses', 'Tersimpan');
            return redirect()->back();
        }
        
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find(Auth::user()->id);
        return view('user.edit')->with('user',$user);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $this->validate(request(), [
            'name' => 'required',
            'password' => 'required',
        ]);

            $user = User::find($id);
            $user->name = $request->get('name');
            $user->password = bcrypt($request->get('password'));
            $user->save();
            Alert::success('Sukses', 'Tersimpan');
            return redirect()->back();
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();
        return redirect()->back();
    }
}

resources/views/user/edit.blade.php
@extends('layouts.app')
@section('content')
<section class="section">
    <div class="section-header">
        <h1>User Akses</h1>
    </div>
    
    @error('email')
    <span class="invalid-feedback" role="alert">
        <strong>{{ $message }}</strong>
    </span>
    @enderror    
    <div class="section-body">
      <h2 class="section-title">Data User</h2>

      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-body">
                <form method="POST" action="{{ route('user.update', Auth::user()->id ) }}" enctype="multipart/form-data">
                    @method('PUT')
                    @csrf
                    <div class="card">
                      <div class="card-header">
                        <h4>Data User</h4>
                      </div>
                      <div class="card-body">
                          <div class="card-body">
                              <div class="form-group">
                                <label >Nama</label>
                                <input type="text" class="form-control"  placeholder="Masukkan nama " id="name" name="name" value="{{ $user->name }}" required>
                                
                              </div>
                              <div class="form-group">
                                <label >Email</label>
                                <input type="email" class="form-control" id="email" name="email" value="{{ $user->email }}" readonly>
                                
                              </div>
                              <div class="form-group">
                                <label >Password</label>
                                <input type="password" class="form-control"  placeholder="Masukkan Password" name="password" required>
                               
                              </div>
                            </div>
                      </div>
          
                      <div class="card-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Update</button>
                      </div>
                    </div>
                  </form>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>







@endsection

resources/views/user/index.blade.php
@extends('layouts.app')
@section('content')
<section class="section">
    <div class="section-header">
        <h1>User Akses</h1>
    </div>
    
    @error('email')
    <span class="invalid-feedback" role="alert">
        <strong>{{ $message }}</strong>
    </span>
    @enderror    
    <div class="section-body">
      <h2 class="section-title">Data User</h2>

      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
                <button type="button" class="btn btn-icon icon-left btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo"><i class="far fa-edit"></i>Masukkan User</button>
                
                
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-striped" id="table-1">
                  <thead>                                 
                    <tr>
                      <th class="text-center">
                        #
                      </th>
                      <th>Nama</th>
                      <th>Email</th>
                      <th>Level Akses</th>
                      <th>Action</th>
                    </tr>
                  </thead> 
                  <tbody>
                    @php
                        $no = 1;
                    @endphp
                    @foreach ($datas as $item)
                    <tr>
                      <td class="text-center">
                        {{ $no++ }}
                      </td>
                      <td>{{ $item->name }}</td>
                      <td>{{ $item->email }}</td>
                      <td>
                        @if ($item->level === 2)
                        <div class="badge badge-danger">USER EXTERNAL</div>                             
                        @endif
                        @if ($item->level === 0)
                        <div class="badge badge-secondary">USER INTERNAL</div>
                        @endif
                        @if ($item->level === 1)
                        <div class="badge badge-primary">SUPER USER</div>
                        @endif
                      </td>
                        <td>
                            @if ($item->id == Auth::user()->id)
                            <div class="badge badge-info">Anda</div>
                            @elseif ($item->level != 1)
                            <form action="{{ route('user.destroy', $item->id) }}"   method="post">
                                {{ csrf_field() }}
                                {{ method_field('delete') }}
                                <button class="btn btn-icon icon-left btn-danger" onclick="return confirm('Anda yakin ingin menghapus data ini?')"> Delete
                                </button>
                            </form>
                            @endif
                            
                        </td>
                      
                    </tr>
                    @endforeach                
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
     
      <div class="modal-body">
        <form method="POST" action="{{ route('user.store') }}" enctype="multipart/form-data">
          @csrf
          <div class="card">
            <div class="card-header">
              <h4>Input Data Objek</h4>
            </div>
            <div class="card-body">
              <div class="form-group">
                <label >Nama</label>
                <input type="text" class="form-control"  placeholder="Masukkan nama " name="name" required>
                
              </div>
              <div class="form-group">
                <label >Email</label>
                <input type="email" class="form-control"  placeholder="Masukkan Email " name="email" required>
                
              </div>
              <div class="form-group">
                <label >Password</label>
                <input type="password" class="form-control"  placeholder="Masukkan Password" name="password" required>
              </div>
              <div class="form-group">
                <label>Level Akses</label>
                <select class="custom-select" name="level" required>
                  <option selected>Pilih</option>
                  <option value="2">External Access</option>
                  <option value="0">Internal Access</option>
                </select>
              </div>
            </div>
            <div class="card-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Save</button>
            </div>
          </div>
        </form>
      </div>
      
    </div>
  </div>
</div>

<div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="editLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
     
      <div class="modal-body">
        <form method="POST" action="{{ route('ow.update', 0 ) }}" enctype="multipart/form-data">
          @method('PUT')
          @csrf
          <div class="card">
            <div class="card-header">
              <h4>Edit Data Objek</h4>
            </div>
            <div class="card-body">
                <div class="card-body">
                    <div class="form-group">
                      <label >Nama</label>
                      <input type="text" class="form-control"  placeholder="Masukkan nama " id="name" name="name" required>
                      
                    </div>
                    <div class="form-group">
                      <label >Email</label>
                      <input type="email" class="form-control"  placeholder="Masukkan Email " id="email" name="email" required>
                      
                    </div>
                    <div class="form-group">
                      <label >Password</label>
                      <input type="password" class="form-control"  placeholder="Masukkan Password" name="password" required>
                     
                    </div>
                    
                  </div>
            </div>

            <div class="card-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Save</button>
            </div>
          </div>
        </form>
      </div>
      
    </div>
  </div>
</div>



@section('script')
<script>
  $('#edit').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Button that triggered the modal
  var id   = button.data('id')
  var name = button.data('name') // Extract info from data-* attributes
  var email = button.data('email')
  // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
  // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
  var modal = $(this)
  modal.find('.modal-body #id').val(id);
  modal.find('.modal-body #name').val(name);
  modal.find('.modal-body #email').val(email);
  

})

$('#tambah').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Button that triggered the modal
  var id   = button.data('id')
  var nama   = button.data('nama')
  
  // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
  // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
  var modal = $(this)
  modal.find('.modal-body #id').val(id);
  modal.find('.modal-body #nama').val(nama);

})






</script>
@endsection

@endsection