routes/web.php
<?php

use App\Http\Controllers\AkomodasiController;
use App\Http\Controllers\EkrafController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\KunAkomodasiController;
use App\Http\Controllers\KunOwController;
use App\Http\Controllers\KunRhuController;
use App\Http\Controllers\OwController;
use App\Http\Controllers\RhuController;
use App\Http\Controllers\UserController;
use App\KunjunganAkomodasi;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['middleware' => 'auth'], function(){
    Route::get('/home', 'HomeController@index')->name('home');
    //##################AKOMODASI#######################
    Route::resource('akomodasi', 'AkomodasiController');
    Route::resource('k_akomodasi', 'KunAkomodasiController');
    Route::get('exportakomodasi/{tahun}', 'KunAkomodasiController@exportAkomodasi')->name('exportakomodasi');
    Route::post('akomodasi.migration', 'AkomodasiController@migration')->name('akomodasi.migration');

    //########### END OF AKOMODASI ROUTE ################

    //############################ OW ######################
    Route::resource('ow', 'OwController');
    Route::resource('k_ow', 'KunOwController');
    Route::get('exportow/{tahun}', 'KunOwController@exportOw')->name('exportow');
    Route::get('exportowasing/{tahun}', 'KunOwController@exportOwAsing')->name('exportowasing');
    Route::post('ow.migration', 'OwController@migration')->name('ow.migration');

    //############## END OF OW ####################

    //########## RHU #############
    Route::resource('rhu', 'RhuController');
    Route::resource('k_rhu', 'KunRhuController');
    Route::get('exportrhu/{tahun}', 'KunRhuController@exportRhu')->name('exportrhu');
    //########## END OF RHU ########

    //########### EKRAF ##################
    Route::resource('ekraf', 'EkrafController')->except('index');
    route::get('ekraf_index/{id}', 'EkrafController@index')->name('ekraf_index');
    Route::get('kurasi/{id}/{code}', 'EkrafController@kurasi')->name('kurasi');
    Route::get('export/{code}','EkrafController@export')->name('ekraf.export');
    Route::post('city', 'HomeController@city')->name('city');
    Route::post('district', 'HomeController@district')->name('district');
    Route::post('village', 'HomeController@village')->name('village');
    //######### END EKRAF ####################
    Route::resource('user', 'UserController');
});

app/Akomodasi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Akomodasi extends Model
{
    protected $table = "akomodasi";
    protected $fillable = ['nama','kamar','tdup','generated_at', 'chse', 'peduli_lindungi', 'whatsapp','migrate'];
    public function kunjungan()
    {
        return $this->hasMany('App\KunjunganAkomodasi', 'akomodasi_id', 'id');
    } 

    public static function akomodasi()
    {
        return Akomodasi::get()->count();
    }

    
    
}

app/Http/Controllers/AkomodasiController.php
<?php

namespace App\Http\Controllers;

use App\Akomodasi;
use App\EkrafAkomodasi;
use App\EkrafAkomodasiKunjungan;
use App\KunjunganAkomodasi;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use RealRashid\SweetAlert\Facades\Alert;
use RealRashid\SweetAlert\Facades\Toast;

class AkomodasiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $curyear = date('2021'); 
        //$curyear = date('Y'); 
        $datas = Akomodasi::where('migrate', 0)->get();
        $record = KunjunganAkomodasi::select([
            DB::raw(DB::raw("DATE_FORMAT(bulan, '%M') as bulan")),
            DB::raw(DB::raw('SUM(jumlah) as jumlah'))
        ])->where(DB::raw("DATE_FORMAT(bulan, '%Y')" ), $curyear)->groupBy('bulan')->get();

        $data = [];
        foreach ($record as $row) {
            # code...
            $data['label'][] = $row->bulan;
            $data['data'][] = (int) $row->jumlah;
        }
        $data['chart_data'] = json_encode($data);
        $kunjunganTahun = KunjunganAkomodasi::selectRaw('year(bulan) year, count(*) data')
        ->groupBy('year')
        ->orderBy('year', 'asc')
        ->get();

        $ekrafakomodasi = EkrafAkomodasi::where('migrate', 0)->get();

        return view('akomodasi.index')->with($data)->with('datas', $datas)->with('kunjunganTahun', $kunjunganTahun)->with('ekrafakomodasi', $ekrafakomodasi);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $akomodasi = new Akomodasi();
        $akomodasi->nama = $request->get('nama');
        $akomodasi->kamar = $request->get('kamar');
        $akomodasi->tdup = $request->get('tdup');
        $akomodasi->chse = $request->get('chse');
        $akomodasi->peduli_lindungi = $request->get('peduli');
        $akomodasi->whatsapp = $request->get('whatsapp');
        $akomodasi->save();
        Alert::success('Sukses', 'Tersimpan');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Akomodasi::find($id);
        return response()->json($product);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $id = $request->get('id');
        $akomodasi = Akomodasi::find($id);
        $akomodasi->nama = $request->get('nama');
        $akomodasi->kamar = $request->get('kamar');
        $akomodasi->tdup = $request->get('tdup');
        $akomodasi->chse = $request->get('chse');
        $akomodasi->peduli_lindungi = $request->get('peduli');
        $akomodasi->whatsapp = $request->get('whatsapp');
        $akomodasi->save();
        Alert::success('Sukses', 'Updated');
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function migration(Request $request)
    {
        $code = $request->CODE;
        $id = $request->id;
        $idakomodasiEkraf = $request->idakomodasiEkraf;
        

        if ($code === 'EXIST') {
            
            //DATA UDAH ADA 
            $akomodasi = Akomodasi::find($id);
            if ($akomodasi->tdup == 'Memiliki' OR $akomodasi->tdup == 'Ya') {$tdup = 1;} else {$tdup = 0;}
            if ($akomodasi->chse == 'Memiliki' OR $akomodasi->chse == 'Ya') {$chse = 1;} else {$chse = 0;}
            if ($akomodasi->peduli_lindungi == 'Memiliki' OR $akomodasi->peduli_lindungi == 'Ya') {$peduli = 1;} else {$peduli = 0;}

            $akomodasiEkrafINS = EkrafAkomodasi::find($idakomodasiEkraf);
            $akomodasiEkrafINS->akomodasi_tdup = $tdup;
            $akomodasiEkrafINS->akomodasi_chse = $chse;
            $akomodasiEkrafINS->akomodasi_vaksin = $peduli;
            $akomodasiEkrafINS->akomodasi_whatsapp = $akomodasi->whatsapp;
            $akomodasiEkrafINS->generated_at = $akomodasi->generated_at;
            $akomodasiEkrafINS->migrate = 1;
            $akomodasiEkrafINS->users_id = Auth::user()->id;
            $akomodasiEkrafINS->save();

            $kunjunagan = KunjunganAkomodasi::where('akomodasi_id', $id)->get();
            $coll = collect($kunjunagan);
            foreach ($coll as $coll) {
                # code...
                $data =[
                    ['bulan' => $coll->bulan, 'jumlah' => $coll->jumlah, 'akomodasi_id'=> $idakomodasiEkraf, 'users_id'=> Auth::user()->id ],
                   ];
                   EkrafAkomodasiKunjungan::insert($data);
            }
            
            //UPDATE AKOMODASI SDK
            $akomodasi->migrate = 1;
            $akomodasi->save();
            toast('Migration Success', 'success');
            return redirect()->back();

        } else {
            //DATA BARU
            $akomodasi = Akomodasi::find($id);
            if ($akomodasi->tdup == 'Memiliki' OR $akomodasi->tdup == 'Ya') {$tdup = 1;} else {$tdup = 0;}
            if ($akomodasi->chse == 'Memiliki' OR $akomodasi->chse == 'Ya') {$chse = 1;} else {$chse = 0;}
            if ($akomodasi->peduli_lindungi == 'Memiliki' OR $akomodasi->peduli_lindungi == 'Ya') {$peduli = 1;} else {$peduli = 0;}
            $akomodasiEkrafINS = new EkrafAkomodasi;
            $akomodasiEkrafINS->akomodasi_nama = $akomodasi->nama;
            $akomodasiEkrafINS->akomodasi_kamar = $akomodasi->kamar;
            $akomodasiEkrafINS->akomodasi_tdup = $tdup;
            $akomodasiEkrafINS->akomodasi_chse = $chse;
            $akomodasiEkrafINS->akomodasi_vaksin = $peduli;
            $akomodasiEkrafINS->akomodasi_whatsapp = $akomodasi->whatsapp;
            $akomodasiEkrafINS->generated_at = $akomodasi->generated_at;
            $akomodasiEkrafINS->migrate = 1;
            $akomodasiEkrafINS->users_id = Auth::user()->id;
            $akomodasiEkrafINS->save();
            $kunjunagan = KunjunganAkomodasi::where('akomodasi_id', $akomodasi->id)->get();
            $coll = collect($kunjunagan);
            foreach ($coll as $coll) {
                # code...
                $data =[
                    ['bulan' => $coll->bulan, 'jumlah' => $coll->jumlah, 'akomodasi_id'=> $akomodasiEkrafINS->id, 'users_id'=> Auth::user()->id ],
                   ];
                   EkrafAkomodasiKunjungan::insert($data);
            }
            //UPDATE AKOMODASI SDK
            $akomodasi->migrate = 1;
            $akomodasi->save();
            toast('Migration Success', 'success');
            return redirect()->back();
        }
       


        
    }
}

resources/views/akomodasi/kunjungan/index.blade.php
@extends('layouts.app')
@section('content')
<section class="section">
    <div class="section-header">
        <h1>Akomodasi</h1>
    </div>
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6 col-12">
          <div class="card card-statistic-1">
            <div class="card-icon bg-primary">
              <i class="far fa-user"></i>
            </div>
            <div class="card-wrap">
              <div class="card-header">
                <h4>Rata - Rata perbulan</h4>
              </div>
              <div class="card-body">
                {{ $avgPerMonth }}
              </div> 
            </div>
          </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-12">
          <div class="card card-statistic-1">
            <div class="card-icon bg-danger">
              <i class="far fa-newspaper"></i>
            </div>
            <div class="card-wrap">
              <div class="card-header">
                <h4>Tahun ini</h4>
              </div>
              <div class="card-body">
                {{ $KunThisYear }}
              </div>
            </div>
          </div>
        </div>         
    </div>
    <div class="row">
      <div class="col-6 col-md-6 col-lg-6">
        <div class="card">
          <div class="card-header">
            <h4>Statistik Line Chart</h4>
          </div>
          <div class="card-body">
            <canvas id="line-chart" >
            </canvas>
          </div>
        </div>
      </div>
      <div class="col-6 col-md-6 col-lg-6">
        <div class="card">
          <div class="card-header">
            <h4>Statistik Pie Chart</h4>
          </div>
          <div class="card-body">
            <canvas id="pie-chart" >
            </canvas>
          </div>
        </div>
      </div>
    </div>

    <div class="section-body">
      <h2 class="section-title">Data Kunjungan {{ $akomodasi->nama }}</h2>

      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-body"> 
              <div class="table-responsive">
                <table class="table table-striped" id="table-1">
                  <thead>                                 
                    <tr>
                      <th class="text-center">
                        #
                      </th>
                      <th>Bulan</th>
                      <th>Jumlah</th>
                      <th>Tahun</th>
                      @if (Auth::user()->level === 1 OR Auth::user()->level === 0)
                      <th>Action</th>
                      @endif
                    </tr>
                  </thead>
                  <tbody>
                    @php
                        $no = 1;
                    @endphp
                    @foreach ($datas as $item)
                    <tr>
                      <td class="text-center">
                        {{ $no++ }}
                      </td>
                      <td>{{ \Carbon\Carbon::parse($item->bulan)->format('F')}}</td>
                      <td >
                          {{ $item->jumlah }}
                      </td>
                      <td>{{ \Carbon\Carbon::parse($item->bulan)->format('Y')}}</td>
                      @if (Auth::user()->level === 1 OR Auth::user()->level === 0))
                      <th>
                        <button type="button" class="btn btn-icon icon-left btn-danger" data-id="{{ $item->id }}" data-jumlah="{{ $item->jumlah }}" data-bulan="{{ \Carbon\Carbon::parse($item->bulan)->format('F')}}" data-toggle="modal" data-target="#edit"><i class="far fa-edit"></i>Edit</button>
                      </th>
                      @endif
                      
                      
                    </tr>
                    @endforeach                
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>

<div class="modal fade" id="tambahkunjungan" tabindex="-1" role="dialog" aria-labelledby="tambahkunjunganLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
       
        <div class="modal-body">
          <form method="POST" action="{{ route('k_akomodasi.store') }}" enctype="multipart/form-data" id="myform">
            @csrf
            <div class="card">
              <div class="card-header">
                <h4>Tambah Kunjungan </h4>
              </div>
              <div class="card-body">
                <div class="form-group">
                  <input type="hidden" class="form-control"  id="id" name="id" value="{{ $akomodasi->id }}" required>
                  <div class="form-group">
                    <label>Bulan</label>
                    <input type="month" class="form-control" name="bulan" readonly>
                  </div>
                  <div class="form-group">
                    <label>Jumlah</label>
                    <input type="number" class="form-control" name="jumlah" id="jumlah" required>
                  </div>
                </div>
              </div>
  
              <div class="card-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save</button>
              </div>
            </div>
          </form>
        </div>
        
      </div>
    </div>
  </div>

<div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="editLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
     
      <div class="modal-body">
        <form method="POST" action="{{ route('k_akomodasi.update', 0 ) }}" enctype="multipart/form-data">
          @method('PUT')
          @csrf
          <div class="card">
            <div class="card-header">
              <h4>Edit kunjungan </h4>
            </div>
            <div class="card-body">
              <div class="form-group">
                <label for="inputAddress">Bulan</label>
                <input type="text" class="form-control"  id="bulan" name="bulan" readonly>
                <label for="inputAddress">Jumlah</label>
                <input type="number" class="form-control"  id="jumlah" name="jumlah" required>
                <input type="hidden" class="form-control"  id="id" name="id" required>
              </div>
            </div>

            <div class="card-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Save</button>
            </div>
          </div>
        </form>
      </div>
      
    </div>
  </div>
</div>

@section('script')
<script>
  $('#edit').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget) // Button that triggered the modal
    var bulan = button.data('bulan')
    var jumlah = button.data('jumlah') // Extract info from data-* attributes
    var id   = button.data('id')
    // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
    // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
    var modal = $(this)
    modal.find('.modal-body #bulan').val(bulan);
    modal.find('.modal-body #jumlah').val(jumlah);
    modal.find('.modal-body #id').val(id);
    
  })
  $(function(){ 
      //get the pie chart canvas
      var cData = JSON.parse('<?php echo $chart_data; ?>');
      var ctx = $("#line-chart");
 
      //pie chart data
      var data = {
        labels: cData.label,
        datasets: [
          {
            label: "Kunjungan",
            data: cData.data,
            borderWidth: 2,
            backgroundColor: '#6777ef',
            borderColor: '#6777ef',
            borderWidth: 2.5,
            pointBackgroundColor: '#ffffff',
            pointRadius: 4,
            fill: false
          }
        ]
      };
 
      //options
      var options = {
        responsive: true,
        title: {
          display: true,
          position: "top",
          text: "Grafik Kunjungan Perbulan Tahun Ini",
          fontSize: 18,
          fontColor: "#111"
        },
        legend: {
          display: false
          
        }
      };
 
      //create Pie Chart class object
      var chart1 = new Chart(ctx, {
        type: "line",
        data: data,
        options: options
      });
 
  });

  $(function(){
      //get the pie chart canvas
      var cData = JSON.parse('<?php echo $chart_data; ?>');
      var ctx = $("#pie-chart");
 
      //pie chart data
      var data = {
        labels: cData.label,
        datasets: [
          {
            label: "Kunjungan",
            data: cData.data,
            borderWidth: 2,
            borderWidth: 2.5,
            pointBackgroundColor: '#ffffff',
            pointRadius: 4,
            backgroundColor: [
              "#E0F2F1",
              "#4DD0E1",
              "#29B6F6",
              "#0091EA",
              "#DCE775",
              "#1D7A46",
              "#CDA776",
              "#F44336",
              "#EF9A9A",
              "#6A1B9A",
              "#26A69A",
              "#E65100",

            ],
            borderColor: [
              "#E0F2F1",
              "#4DD0E1",
              "#29B6F6",
              "#0091EA",
              "#DCE775",
              "#1D7A46",
              "#CDA776",
              "#F44336",
              "#EF9A9A",
              "#6A1B9A",
              "#26A69A",
              "#E65100",
            ],
            borderWidth: [1, 1, 1, 1, 1,1,1]
          }
        ]
      };
 
      //options
      var options = {
        responsive: true,
        title: {
          display: true,
          position: "top",
          text: "Grafik Kunjungan Perbulan Tahun Ini",
          fontSize: 18,
          fontColor: "#111"
        },
        legend: {
          display: true,
          position: "bottom",
          labels: {
            fontColor: "#333",
            fontSize: 10
          }
          
        }
      };
 
      //create Pie Chart class object
      var chart1 = new Chart(ctx, {
        type: "pie",
        data: data,
        options: options
      });
 
  });

  jQuery.validator.setDefaults({
  debug: true,
  success: "valid"
  });
  $( "#myform" ).validate({
    rules: {
      jumlah: {
        required: true,
        number: true
      }
    }
  });
  
  
  
  </script>
@endsection

@endsection