routes/web.php
<?php

use App\Http\Controllers\AkomodasiController;
use App\Http\Controllers\EkrafController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\KunAkomodasiController;
use App\Http\Controllers\KunOwController;
use App\Http\Controllers\KunRhuController;
use App\Http\Controllers\OwController;
use App\Http\Controllers\RhuController;
use App\Http\Controllers\UserController;
use App\KunjunganAkomodasi;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['middleware' => 'auth'], function(){
    Route::get('/home', 'HomeController@index')->name('home');
    //##################AKOMODASI#######################
    Route::resource('akomodasi', 'AkomodasiController');
    Route::resource('k_akomodasi', 'KunAkomodasiController');
    Route::get('exportakomodasi/{tahun}', 'KunAkomodasiController@exportAkomodasi')->name('exportakomodasi');
    Route::post('akomodasi.migration', 'AkomodasiController@migration')->name('akomodasi.migration');

    //########### END OF AKOMODASI ROUTE ################

    //############################ OW ######################
    Route::resource('ow', 'OwController');
    Route::resource('k_ow', 'KunOwController');
    Route::get('exportow/{tahun}', 'KunOwController@exportOw')->name('exportow');
    Route::get('exportowasing/{tahun}', 'KunOwController@exportOwAsing')->name('exportowasing');
    Route::post('ow.migration', 'OwController@migration')->name('ow.migration');

    //############## END OF OW ####################

    //########## RHU #############
    Route::resource('rhu', 'RhuController');
    Route::resource('k_rhu', 'KunRhuController');
    Route::get('exportrhu/{tahun}', 'KunRhuController@exportRhu')->name('exportrhu');
    //########## END OF RHU ########

    //########### EKRAF ##################
    Route::resource('ekraf', 'EkrafController')->except('index');
    route::get('ekraf_index/{id}', 'EkrafController@index')->name('ekraf_index');
    Route::get('kurasi/{id}/{code}', 'EkrafController@kurasi')->name('kurasi');
    Route::get('export/{code}','EkrafController@export')->name('ekraf.export');
    Route::post('city', 'HomeController@city')->name('city');
    Route::post('district', 'HomeController@district')->name('district');
    Route::post('village', 'HomeController@village')->name('village');
    //######### END EKRAF ####################
    Route::resource('user', 'UserController');
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
  <title>Dashboard &mdash; EKONOMI KREATIF</title>

  <!-- General CSS Files -->
  <link rel="stylesheet" href="{{ asset('assets/modules/bootstrap/css/bootstrap.min.css') }}">
  <link rel="stylesheet" href="{{ asset('assets/modules/fontawesome/js/all.min.js') }}">
  <link rel="stylesheet" href="{{ asset('assets/modules/fontawesome/css/all.min.css') }}">
  <!-- CSS Libraries -->
  <link rel="stylesheet" href="{{ asset('assets/modules/datatables/datatables.css') }}">
  <link rel="stylesheet" href="{{ asset('assets/modules/datatables/DataTables-1.10.16/css/dataTables.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('assets/modules/datatables/Select-1.2.4/css/select.bootstrap4.min.css') }}">
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

  <!-- Template CSS -->
  <link rel="stylesheet" href="{{ asset('assets/css/style.css') }}">
  <link rel="stylesheet" href="{{ asset('assets/css/components.css') }}">
<!-- Start GA -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-94034622-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-94034622-3');
</script>
<!-- /END GA --></head>

<body>
  <div id="app">
    <div class="main-wrapper main-wrapper-1">
      <div class="navbar-bg"></div>
      @include('layouts.topnav')
      @include('layouts.sidebar')
      @include('sweetalert::alert')

      <!-- Main Content -->
      <div class="main-content">
        @yield('content')
      </div>
      
    </div>
  </div>

  <!-- General JS Scripts -->
  <script src="{{ asset('assets/modules/jquery.min.js') }}"></script>
<script src="{{asset("https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.4/axios.js") }}"></script>
  <script src="{{ asset('assets/modules/popper.js') }}"></script>
  <script src="{{ asset('assets/modules/tooltip.js') }}"></script>
  <script src="{{ asset('assets/modules/bootstrap/js/bootstrap.min.js') }}"></script>

  <script src="{{ asset('assets/modules/nicescroll/jquery.nicescroll.min.js') }}"></script>
  <script src="{{ asset('assets/modules/moment.min.js') }}"></script>
  <script src="{{ asset('assets/js/stisla.js') }}"></script>
  <script src="{{ asset('assets/modules/select2/dist/js/select2.min.js') }}"></script>
  
  <!-- JS Libraies -->
  <script src="{{ asset('assets/modules/simple-weather/jquery.simpleWeather.min.js') }}"></script>
  <script src="{{ asset('assets/modules/chart.min.js') }}"></script>
  <script src="{{ asset('assets/modules/jqvmap/dist/jquery.vmap.min.js') }}"></script>
  <script src="{{ asset('assets/modules/jqvmap/dist/maps/jquery.vmap.world.js') }}"></script>
  <script src="{{ asset('assets/modules/summernote/summernote-bs4.js') }}"></script>
  <script src="{{ asset('assets/modules/chocolat/dist/js/jquery.chocolat.min.js') }}"></script>

  <script src="{{ asset('assets/modules/datatables/datatables.min.js') }}"></script>
  <script src="{{ asset('assets/modules/datatables/DataTables-1.10.16/js/dataTables.bootstrap4.min.js') }}"></script>
  <script src="{{ asset('assets/modules/datatables/Select-1.2.4/js/dataTables.select.min.js') }}"></script>
  <script src="{{ asset('assets/modules/jquery-ui/jquery-ui.min.js') }}"></script>

  <!-- Page Specific JS File -->
  <script src="{{ asset('assets/js/page/modules-datatables.js') }}"></script>

  <!-- Page Specific JS File -->
  <script src="{{ asset('assets/js/page/index-0.js') }}"></script>
  
  <!-- Template JS File -->
  <script src="{{ asset('assets/js/scripts.js') }}"></script>
  <script src="{{ asset('assets/js/custom.js') }}"></script>

  <!--CHART JS-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
  
  <script>
    $(document).ready(function() {
    $('.js-example-basic-single').select2();
});
  </script>
  
  @stack('script')
  
</body>
</html>

resources/views/layouts/sidebar.blade.php
<div class="main-sidebar sidebar-style-2">
    <aside id="sidebar-wrapper">
      <div class="sidebar-brand">
        <a href="{{ route('home') }}"><img alt="image" width="120" height="50" src="{{ asset('assets/img/ekraf.png') }}"></a>
      </div>
      <div class="sidebar-brand sidebar-brand-sm">
        <a href="{{ route('home') }}"><img alt="image"  width="30" height="30" src="{{ asset('assets/img/ekraf-medium.png') }}"></a>
      </div>
      <ul class="sidebar-menu">
        <li class="dropdown  {{ (request()->is('home*')) ? 'active' : '' }}">
          <a href="{{ route('home') }}" class="nav-link "><i class="fas fa-fire"></i><span>DASHBOARD</span></a>
        </li>
        <li class="dropdown {{ (request()->is(['ekraf_index/0'])) ? 'active' : '' }}">
            <a href="{{ route('ekraf_index',0) }}" class="nav-link"><i class="fas fa-swimming-pool"></i> <span>EKRAF</span></a>
        </li>

        <li class="dropdown {{ (request()->is(['ekraf_index/1'])) ? 'active' : '' }}">
          <a href="{{ route('ekraf_index',1) }}" class="nav-link"><i class="fas fa-swimming-pool"></i> <span>KURASI</span></a>
      </li>
        @if (Auth::user()->level == 1)
        <li class="menu-header">Access</li>
        <li class="dropdown {{ (request()->is(['user*'])) ? 'active' : '' }}">
            <a href="{{ route('user.index') }}" class="nav-link"><i class="fas fa-users"></i> <span>USER</span></a>
        </li>
        @endif
        
      </ul>

      <div class="mt-4 mb-4 p-3 hide-sidebar-mini">
        <a href="https://docs.google.com/document/d/1Q0mENLNhf7JPvET8uqzymEq4Qt7iP_MLzJXkkqdAN4g/edit?usp=sharing" target="_blank" class="btn btn-primary btn-lg btn-block btn-icon-split">
          <i class="fas fa-rocket"></i> Documentation
        </a>
      </div>        
    </aside>
  </div>

resources/views/layouts/topnav.blade.php
<nav class="navbar navbar-expand-lg main-navbar">
    <form class="form-inline mr-auto">
      <ul class="navbar-nav mr-3">
        <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
      </ul>
    </form>
    <ul class="navbar-nav navbar-right">
      <li class="dropdown dropdown-list-toggle"><a href="#" data-toggle="dropdown" class="nav-link nav-link-lg message-toggle beep"><i class="far fa-envelope"></i></a>
        <div class="dropdown-menu dropdown-list dropdown-menu-right">
          <div class="dropdown-header">Segera Hadir
            <div class="float-right">
              <a href="#">Mark All As Read</a>
            </div>
          </div>
          
          <div class="dropdown-footer text-center">
            <a href="#">View All <i class="fas fa-chevron-right"></i></a>
          </div>
        </div>
      </li>
      <li class="dropdown dropdown-list-toggle"><a href="#" data-toggle="dropdown" class="nav-link notification-toggle nav-link-lg beep"><i class="far fa-bell"></i></a>
        <div class="dropdown-menu dropdown-list dropdown-menu-right">
          <div class="dropdown-header">Segera Hadir
            <div class="float-right">
              <a href="#">Mark All As Read</a>
            </div>
          </div>
          
          <div class="dropdown-footer text-center">
            <a href="#">View All <i class="fas fa-chevron-right"></i></a>
          </div>
        </div>
      </li>
      <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
        <img alt="image" src="{{ asset('assets/img/avatar/avatar-1.png') }}" class="rounded-circle mr-1">
        <div class="d-sm-none d-lg-inline-block">Hi, {{ Auth::user()->name }}</div></a>
        <div class="dropdown-menu dropdown-menu-right">
          <div class="dropdown-title">Logged as {{ Auth::user()->name }} </div>
          
          <div class="dropdown-divider"></div>
          <a href="{{ route('user.edit', Auth::user()->id) }}" class="dropdown-item has-icon text-success">
            <i class="fas fa-edit"></i> Edit
          </a>
          <a href="{{ route('logout') }}" class="dropdown-item has-icon text-danger" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
            <i class="fas fa-sign-out-alt"></i> Logout
          </a>
          <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
            @csrf
        </form>
        </div>
      </li>
    </ul>
  </nav>